version: '3.7'

services:
  node-server:
    container_name: node
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 120s   # ← เพิ่มเป็น 2 นาที

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8080:80"